### ISSUE TITLE
Android: processIntent is broken for Intent.ACTION_VIEW if the scheme of the uri is content.

### ISSUE THREAD

**Issue by pazos** [buggins/coolreader#126]
The behaviour is not something new, but each day is more common because of the uriExposedException on api level 24+. That makes most filemanagers forced to feed a content scheme via a fileProvider.

I see you're trying to figure out the file path in https://github.com/buggins/coolreader/blob/master/android/src/org/coolreader/CoolReader.java#L298-L354. This fails on most filemanagers, which leds to a message like:

![device-2020-01-27-211748](https://user-images.githubusercontent.com/975883/73210401-81d7a480-414a-11ea-955c-e49cac41600d.png)

On KOReader we use a workaround for figuring out the path of a file shared via fileProvider. That should work on Coolreader too.

The implementation is [here](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/FileUtils.kt#L35-L80)

On our case if the uri contains a content that cannot be resolved to a file path we just return null and avoid further processing. In the case of Coolreader it could do the same or, alternatively, import the file. Again, the code for doing that in ko is available [here](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/FileUtils.kt#L82-L161)

Please @virxkane, @buggins , consider that. At least the workaround to figure the file path.

**Comment by virxkane** [comment]
@pazos thank you. I will try to fix this. Which file manager I must use to get this error?

**Comment by virxkane** [comment]
And can you upload your epub test files to test the new features that we got with PR #125?

**Comment by pazos** [comment]
> Which file manager should I use to get this error?

The screenshots was made using [Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files/) but can be reproduced on any other filemanager, like Explorer, Root Explorer, Simple Explorer, etc.

An example of an app that works fine in Coolreader is [amaze](https://f-droid.org/en/packages/com.amaze.filemanager/). This is built with a low targetApi and send files to coolreader.

A good app to figure out which intent is sent is [intercept intent](https://f-droid.org/en/packages/de.k3b.android.intentintercept/)

> And can you upload your epub test files to test the new features that we got with PR #125?

@poire-z knows more and can anwser all your questions about crengine thingies. I'm just happy to see his improvements working on coolreader too :)

**Comment by virxkane** [comment]
Ok, thank you.

**Comment by pazos** [comment]
In fact #129 fixes the issue with both Material Files and Root Explorer, thanks!
