### ISSUE TITLE
3.2.39 broken table view and some others

### ISSUE THREAD

**Issue by ssten** [buggins/coolreader#137]
After updating to 3.2.39 I've find that coolreader begins incorrectly display tables, missing empty lines and change behaviour in display documet's sections.

Previous (expected) view
![3 2 2 1-r2](https://user-images.githubusercontent.com/2209401/81501718-77e54600-92e2-11ea-8fc1-d7372a0bf5a4.png)

3.2.39 view:
![3 2 39](https://user-images.githubusercontent.com/2209401/81501719-79167300-92e2-11ea-9180-05f2399f9fcb.png)

**Comment by poire-z** [comment]
> After updating to 3.2.39 I've find that coolreader begins incorrectly display tables, missing empty lines and change behaviour in display documet's sections.

I don't see the missing lines, and dunno about document sections. Is that a FB2 document?

For the changes in tables rendering, I don't think it's incorrect in an EPUB context (but may be it is in the FB2 context): it's some change introduced in KOReader (and picked by CR 3.2.29) to display tables as the CSS specs say and as browsers do (see https://github.com/koreader/crengine/pull/243).
If you wish them to take all the screen width, add into your fb2.css or epub.css:
`table { width: 100% !important; }`
And if you want borders:
`table, tcaption, tr, th, td { border: black solid 1px; border-collapse: collapse; }`

If that's expected for FB2 (where publishers may not style tables), well, it might then be added in the shipped fb2.css (but not in epub.css, as EPUB publishers may expect "shrink to fit" and "no border" to be the default, and tweak that only when needed).

**Comment by ssten** [comment]
It is the same fb2 file, generated from first example of OOoFBTools.
ExportToFB21_example-1.fb2

**Comment by virxkane** [comment]
@ssten Is it still relevant, or can it be closed?

**Comment by ssten** [comment]
3.2.57, table display is OK.
