### ISSUE TITLE
Android version: Swapped "comment" and "correction" in sent bookmarks.

### ISSUE THREAD

**Issue by uap4** [buggins/coolreader#153]
In the resulting text, when a bookmark is sent, instead of "comment" is written "correction", and vice versa. Exporting to a file does not have this problem. Maybe remove the "!" on this line?
https://github.com/buggins/coolreader/blob/a0aff34d866abaf33de8b5cd7abeb0542de0f3dd/android/src/org/coolreader/crengine/BookInfo.java#L224
В получившемся тексте, когда закладки отправляются, вместо "comment" написано "correction", и наоборот. При экспорте в файл этой проблемы нет. Может,  убрать "!" в этой строке?

upd. Similar to https://github.com/buggins/coolreader/commit/d541525851f369f5982048efb42fe7bb02096e4f

**Comment by virxkane** [comment]
Yes, it looks like that.

**Comment by uap4** [comment]
Thank. In cr3.2.45 release this works fine.
