### ISSUE TITLE
не хочет собираться под linux

### ISSUE THREAD

**Issue by sinsan-hub** [buggins/coolreader#178]
Не хочет собираться прога под линукс, в последних версиях.
Более ранние собирались, например в cr3.2.35 было всё ОК.
Вот такая ошибка:
coolreader-cr3.2.45/crengine/src/textlang.cpp:678:40: error: ‘LBP_ZWJ’ was not declared in this scope
     _lb_props[n++] = { 0x00AD, 0x00AD, LBP_ZWJ };

**Comment by virxkane** [comment]
Update **libunibreak** library to version 4.0.

**Comment by virxkane** [comment]
In #307 added:
277755179bb0998236aabbdc62b236f10c2aa409 Updated cmake modules: detect version.
94af32a791cce58f4b91fad35ca167ea21132c3a Set minimum required versions for thirdparty in CMakeLists.txt
