### ISSUE TITLE
Bogus font compatibility message opening EPUBs

### ISSUE THREAD

**Issue by Carmina16** [buggins/coolreader#233]
https://github.com/buggins/coolreader/blob/d0026212a34e874ba3e670fa14b5f2c1a181848e/cr3qt/src/cr3widget.cpp#L1090

There is an error somewhere in this method chain: some EPUBs contain a fully specified language tag, like "pt-BR", which is passed here, but the font catalog stores bare language names, so it is not found. The country, script, and variant parts should be split from the language code somewhere.

**Comment by virxkane** [comment]
Fixed in Android frontend in #100.
For Qt not fixed yet.

**Comment by virxkane** [comment]
@Carmina16 Could you please test this #235.

**Comment by virxkane** [comment]
Significantly improved in #302.
