### ISSUE TITLE
Massive feature degradation

### ISSUE THREAD

**Issue by vsemozhetbyt** [buggins/coolreader#269]
I am using now mobile beta 3.2.53-1 on Android 7 on Redmi 4A. Since one of the last updates, I've lost the toolbar and most of the settings options, the settings dialog now has just one tab with some basic options. Is it intended degradation?

**Comment by virxkane** [comment]
I think you are on wrong way: screenshots 1-3:
![1_sz](https://user-images.githubusercontent.com/36960933/111040389-38304300-844c-11eb-9ef1-96733aff317a.png)
![2_sz](https://user-images.githubusercontent.com/36960933/111040394-3b2b3380-844c-11eb-86c8-64aff6b1a556.png)
![3_sz](https://user-images.githubusercontent.com/36960933/111040400-3d8d8d80-844c-11eb-8e1a-64c456d56f36.png)
It's option for internal file browser!

So, open any book, tap in the center of the screen, the reading menu should appear.
![4_sz](https://user-images.githubusercontent.com/36960933/111040508-a543d880-844c-11eb-8c1b-c53b72b4499f.png)
And the familiar program settings dialog will open, from which nothing was removed!
Or you can make a long tap and then the settings dialog will also open.
![6_sz](https://user-images.githubusercontent.com/36960933/111040593-11bed780-844d-11eb-8c3d-26d67daef995.png)
Check the highlighted parameters to show toolbar.

**Comment by vsemozhetbyt** [comment]
Thank you a lot. And I am sorry for the fuss.

Unfortunately, it seems I've driven myself into a trap. It seems I've set all simple and long taps to no operation except some taps for page turning, and then in some time I've hidden the toolbar. So now I cannot open the main settings in a simple way(

**Comment by vsemozhetbyt** [comment]
Fixed by deleting the settings ini file and resetting. Sorry again and thanks.
