### ISSUE TITLE
Going back after following a link.

### ISSUE THREAD

**Issue by roundoutandabout** [buggins/coolreader#281]
In the `.epub` document, how to go back to the initial position after I followed a link?
The link points to another position in the document.
I thought that the tap action 'Back' is responsible for this, but it just throws me to the app's main screen.

Android version: 10
CoolReader version: 3.2.55-1

**Comment by plotn** [comment]
@roundoutandabout , could you attach the document (for example) ?

**Comment by roundoutandabout** [comment]
@plotn hi, here's the OnionShare link to the document that I have problem with (open with Tor browser):
http://zsxqocejese4lh5o6vsp2n3gjcdoz5wcjboyqqj6fnaq5yqs3lnnrxyd.onion

**Comment by plotn** [comment]
@roundoutandabout , it is written, that onion-site not found (I'm doing under tor, for sure)

**Comment by roundoutandabout** [comment]
@plotn you're right, sorry. I have updated the link.

**Comment by plotn** [comment]
скачал, посмотрел. Короче говоря здесь работает не системная кнопка "назад", а внутренняя ReaderAction "назад", которую можно вынести на панель или назначить на тапзону

**Comment by roundoutandabout** [comment]
@plotn okay, thanks a lot for looking into this!
Somehow the tap action "Back" didn't work for me at that time, but now I can't reproduce it. 
Anyway, I think we can close the issue, thanks again!
