### ISSUE TITLE
Blurry font rendering on a high DPI display

### ISSUE THREAD

**Issue by efermi** [buggins/coolreader#292]
With the Qt version of the app on a high DPI display the text in the book's canvas is blurry, not rendered properly.
App version: 3.2.57-1
O/S: Manjaro Linux
Global scaling factor: 2

How it looks compared to unscaled (bottom):
![Screenshot_20210524_162930](https://user-images.githubusercontent.com/3966555/119357348-1d7e1400-bcb0-11eb-9fe1-2620100c8273.png)
![Screenshot_20210524_163117](https://user-images.githubusercontent.com/3966555/119357350-1e16aa80-bcb0-11eb-810c-24e839339e1d.png)

**Comment by virxkane** [comment]
@efermi Can you test 3.2.57 with this patch from #293?
https://patch-diff.githubusercontent.com/raw/buggins/coolreader/pull/293.patch

**Comment by efermi** [comment]
Works for me, although the UI widgets remain unscaled.
![Screenshot_20210524_222024](https://user-images.githubusercontent.com/3966555/119397616-115d7b00-bcdf-11eb-8ceb-1fab5e0f871b.png)

**Comment by virxkane** [comment]
> UI widgets remain unscaled.

Menu, setting dialog, about dialog is scaled. Not scaled toolbar icons, scrollbar. Or something else?
I don't know about HiDPI in Qt5 enough, so for now it's all that I can do. Maybe someone will improve it.

**Comment by efermi** [comment]
The fonts are scaled, but not the widgets themselves. Compare patched and original (right):
![Screenshot_20210524_231354](https://user-images.githubusercontent.com/3966555/119402755-0eb25400-bce6-11eb-9171-47b8c8197e4f.png)
Without the patch everything is scaled properly except for the fonts on the book's canvas, and with the patch the fonts everywhere become scaled properly, but the widgets are left unscaled.

**Comment by virxkane** [comment]
> The fonts are scaled, but not the widgets themselves.

Yes indeed. 
Actually we have to disable HiDPI scaling for only one widget (CR3View), but I can't find how to do this.
So, disable it for all application widgets.

**Comment by virxkane** [comment]
@efermi Ok, should we apply this patch in upstream or it's too ugly?

**Comment by efermi** [comment]
I think you should, overall I consider this to be an improvement, fonts are rendered perfectly everywhere now. Only few widgets remain really hard to use, namely the toolbar and the scrollbar and I consider them to be less important than the text.

**Comment by virxkane** [comment]
@efermi
> I think you should, overall I consider this to be an improvement, fonts are rendered perfectly everywhere now. Only few widgets remain really hard to use, namely the toolbar and the scrollbar and I consider them to be less important than the text.

This drawbacks fixed.
Please test this patch: [True-HiDPI-support.zip](https://github.com/buggins/coolreader/files/7874198/True-HiDPI-support.zip)
I'm too lazy to create a pull request, if you want to do it yourself.

**Comment by efermi** [comment]
I've tested the patch, everything looks right, thanks @virxkane! I'll try to put together a PR some time later if you don't do it yourself first.

**Comment by efermi** [comment]
Hello @virxkane, there is a bug with the color preview widget, the center of the square stays white, while only the border around it changes with the selected color.
![Screenshot_20220116_205700](https://user-images.githubusercontent.com/3966555/149671905-5a58ff79-1e6b-4b4e-8354-0373bee28a08.png)

**Comment by virxkane** [comment]
> Hello @virxkane, there is a bug with the color preview widget, the center of the square stays white, while only the border around it changes with the selected color.

Hello. Try next patch:
```diff
diff --git a/cr3qt/src/settings.cpp b/cr3qt/src/settings.cpp
index 9aff7b327..c676ee50a 100644
--- a/cr3qt/src/settings.cpp
+++ b/cr3qt/src/settings.cpp
@@ -887,6 +887,7 @@ void SettingsDlg::setBackground( QWidget * wnd, QColor cl )
 {
     QPalette pal( wnd->palette() );
     pal.setColor( QPalette::Window, cl );
+    pal.setColor( QPalette::Base, cl );
     wnd->setPalette( pal );
 }
 
```

**Comment by efermi** [comment]
This fixes it. I've also noticed that chapter marks in the page header are shorter now, is it also a bug?

**Comment by virxkane** [comment]
> I've also noticed that chapter marks in the page header are shorter now, is it also a bug?

I think - no.
Starting from PR #277, chapter markers are scaled according to DPI, when using the patch in [#292 (comment)](https://github.com/buggins/coolreader/issues/292#issuecomment-1013604699) DPI is set based on screen parameters.
```cpp
void CR3View::updateDefProps()
{
    _data->_props->setStringDef( PROP_WINDOW_FULLSCREEN, "0" );
    _data->_props->setStringDef( PROP_WINDOW_SHOW_MENU, "1" );
    _data->_props->setStringDef( PROP_WINDOW_SHOW_SCROLLBAR, "1" );
    _data->_props->setStringDef( PROP_WINDOW_TOOLBAR_SIZE, "1" );
    _data->_props->setStringDef( PROP_WINDOW_SHOW_STATUSBAR, "0" );
    _data->_props->setStringDef( PROP_APP_START_ACTION, "0" );

#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0)
#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)
    QScreen* screen = this->screen();
#else
    QScreen* screen = QGuiApplication::primaryScreen();
#endif
    lString32 str;
    int d = (int)screen->logicalDotsPerInch();
    // special workaround for MacOS
    if (72 == d)
        d = 96;
    str.appendDecimal(d);
    _data->_props->setString( PROP_RENDER_DPI, str );
    // But we don't apply PROP_RENDER_SCALE_FONT_WITH_DPI property,
    // since for now we are setting the font size in pixels.
#endif

    QStringList styles = QStyleFactory::keys();
    QStyle * s = QApplication::style();
    QString currStyle = s->objectName();
    CRLog::debug("Current system style is %s", currStyle.toUtf8().data() );
    QString style = cr2qt(_data->_props->getStringDef( PROP_WINDOW_STYLE, currStyle.toUtf8().data() ));
    if ( !styles.contains(style, Qt::CaseInsensitive) )
        _data->_props->setString( PROP_WINDOW_STYLE, qt2cr(currStyle) );
}
```

**Comment by efermi** [comment]
All right then, I'll submit the PR shortly.
