### ISSUE TITLE
Coudn't correctly install cr

### ISSUE THREAD

**Issue by nagayev** [buggins/coolreader#300]
Hello. I installed cool reader few minutes ago via rpm package from https://raw.githubusercontent.com/rpmsphere/x86_64/master/c/coolreader3-3.0.56-19.1.x86_64.rpm. And after I tried to ran cr3 I got this error:
```
2021/06/23 22:46:55.8950 ERROR Canot load translation file cr3_en_US from dir /usr/share/cr3/i18n/
2021/06/23 22:46:55.9145 ERROR Error opening file /home/marat/.cr3/cr3.ini for reading
2021/06/23 22:46:55.9146 ERROR Cannot load settings from file /home/marat/.cr3/cr3.ini
2021/06/23 22:46:55.9179 ERROR Error opening file /usr/share/cr3/cr3.ini for reading
2021/06/23 22:46:55.9179 ERROR Cannot load settings from file /usr/share/cr3/cr3.ini
2021/06/23 22:46:55.9183 ERROR Error opening file /usr/share/cr3/cr3hist.bmk for reading
2021/06/23 22:46:55.9183 ERROR Error opening file /home/marat/.cr3/cr3hist.bmk for reading
2021/06/23 22:46:55.9184 ERROR Error opening file /home/marat/.cr3/fb2.css for reading
Segmentation fault (core dumped)
```
It looks like there aren't postinstall script in this rpm and cr3 can't find styles and it's files.

**Comment by virxkane** [comment]
@nagayev This happens when you use a 9-year old version, although there is an actual, modern one.

**Comment by nagayev** [comment]
@virxkane Thanj you.
Can I install newer one?

**Comment by virxkane** [comment]
@nagayev 
First link in google:
https://src.fedoraproject.org/rpms/coolreader
