### ISSUE TITLE
Decreased image quality for bigger pictures

### ISSUE THREAD

**Issue by IMMSPgisgroup** [buggins/coolreader#305]
As I see in Android version this application decreases image quality for bigger pictures in epub format. This isn`t very good for such images, as maps, for example.
P.S. Is this repository is source for Cool Reader on Google Play?

**Comment by virxkane** [comment]
> Is this repository is source for Cool Reader on Google Play?

Yes it is.

> As I see in Android version this application decreases image quality for bigger pictures in epub format. This isn`t very good for such images, as maps, for example.

Can you provide such epub-files for test purposes? This is most likely the result of non-integer (fractional) scaling.

**Comment by IMMSPgisgroup** [comment]
>Can you provide such epub-files for test purposes?you provide such epub-files for test purposes?

[Screenshot_20210814_010209_org sufficientlysecure viewer](https://user-images.githubusercontent.com/33963849/129422953-80c52577-3d1a-4342-8565-d98cde96b085.jpg)
[Screenshot_20210814_005929_org coolreader](https://user-images.githubusercontent.com/33963849/129422971-6a1be9a3-3ae1-4215-8101-aa4dc3d5c027.jpg)
Some screenshotes from Document Viewer and Cool Reader.
[Sample book with image.epub.zip](https://github.com/buggins/coolreader/files/6985374/Sample.book.with.image.epub.zip) - sample book with map created from random historic book. It has zip extension, but this only for adding to comment.

**Comment by virxkane** [comment]
@IMMSPgisgroup The reason was different.
