### ISSUE TITLE
Coolreader has it been abandoned 

### ISSUE THREAD

**Issue by Dnkhatri** [buggins/coolreader#334]
@virxkane @buggins 

Hi it seems Buggins has disappeared and coolreader abandoned, I know @virxkane does not have access to produce compatible apk but I hope someone can create a github action to make apk so that people can merge commits and create their own apks till or if coolreader is ever revived.

**Comment by Mathnerd314** [comment]
There is koreader fork, quite active: https://github.com/koreader/crengine

**Comment by Dnkhatri** [comment]
> There is koreader fork, quite active: https://github.com/koreader/crengine

Thats the crengine  I am talking about coolreader app  I don't like koreader gui

**Comment by plotn** [comment]
@Dnkhatri, we are alive too (if interested):
https://github.com/plotn/coolreader
