### ISSUE TITLE
Patch to Fix: Qt5, wxGTK2.8, wxGTK3.0 build fails and some other issues.

### ISSUE THREAD

**Issue by band-a-prend** [buggins/coolreader#4]
* Fix Qt5 build fails ( https://sourceforge.net/p/crengine/bugs/370/ )
* Fix wxwidgets build fails ( https://sourceforge.net/p/crengine/bugs/371/ )

Info:
Patch allows to build Coolreader3 with Qt5 or wxWindgets GUI for Linux systems.
Qt5 build early failed due to absence of "-std=c++11 -fPIC" options in ../cr3qt/CMakeLIsts.txt
and absence of Qt5 libraries in linking library list of ../cr3qt/CMakeLIsts.txt.
wxWidgets build early failed due to absence of "fonconfig" in linking library list of ../cr3wx/CMakeLIsts.txt.

Coolreader3 is compiling now both for wxGTK 2.8 and wxGTK 3.0 via internal conditional choosing of wxGTK version.
NOTE: wxGTK-gtk3:3.0  (that is not the same as wxGTK 3.0) is compiling too but GUI is corrupted (for example a toolbar has no icons displaying).

Also...
* Adding installation of cr3.{desktop, png, xmp} files to add CoolReader3 icon to application menu when WX GUI was compiled.
* "iCCP: known incorrect sRGB profile" warning popup window when "Toolbar size" is setting to "Medium buttons" in WX GUI application is disabled in patch (
![iccp_known_incorrect_srgb_profile](https://user-images.githubusercontent.com/18756734/30000004-755e5688-9065-11e7-97f6-235aed704835.png)
)
This is the temporary solution until upstream of Coolreader3 will fix iCCP profiles of "22x22/*.png" icons. See related wxGTK issue: http://trac.wxwidgets.org/ticket/15331  for more details.
* The wxWidgets version is displayed now in "About" window of WX GUI.
* Copyright is changed to appropriate the date of CREngine library release date and date of "CoolReader 3.1.2-71" tag. That is "(c) 1998-2015 Vadim Lopatin" and CREngine build date to "2015-07-02".

Preview of patch (as diff) in Gentoo buggzilla: https://bugs.gentoo.org/attachment.cgi?id=491992&action=diff
Raw (as text): https://629720.bugs.gentoo.org/attachment.cgi?id=491992&action=diff&format=raw

Please do a review of this patch. I hope it will be useful.

Maybe it worth to change "(c) 1998-2015 Vadim Lopatin" to "(c) 1998-2017 Vadim Lopatin" for master branch as patch was made for tag "3.1.2-71" branch of 2015 year.

Or patch with 2017 years dates except of CREngine build date (see attachment coolreader_qt5_wx_build_fix_git_version.txt):

[coolreader_qt5_wx_build_fix_git_version.txt](https://github.com/buggins/coolreader/files/1272656/coolreader_qt5_wx_build_fix_git_version.txt)

**Comment by band-a-prend** [comment]
This issue can be closed as RESOLVED as Qt5 issue was fixed in  #14
and other wxWIdgets issues was fixed in #16.

**Comment by buggins** [comment]
Fixed by merging pull requests
