### ISSUE TITLE
How to build this library for android?

### ISSUE THREAD

**Issue by zhjunliu** [buggins/coolreader#5]

**Comment by buggins** [comment]
Use Eclipse with Android SDK - open project from crengine/android dir.

**Comment by zhjunliu** [comment]
The compiled cr3engine-3-1-1.so is too large(9MB),  How do I remove unnecessary code from Android?

**Comment by buggins** [comment]
Check jni/Application.mk for APP_OPTIM
Ensure it's set to release, not debug.

    APP_OPTIM := release

**Comment by buggins** [comment]
Will put instructions here:

https://github.com/buggins/coolreader/wiki/developent-environment-android

(TODO)

**Comment by buggins** [comment]
Wiki is updated: https://github.com/buggins/coolreader/wiki/developent-environment-android

Closing this issue as resolved.
