### ISSUE TITLE
Recognize Energy Sistem eReaders as Eink devices

### ISSUE THREAD

**Issue by pazos** [buggins/coolreader#68]
Hi, first of all, thanks @buggins for your wonderful software!

I see that @virxkane added support for onyx devices. I would like to use a subset of that to add support for energy sistem ereaders (they're just another boyue clone based on rk3026 platform).

I tested that Onyx fast update works on my device by changing device brand and device manufacturer. High quality & fast mode 2 didn't work.

The way to properly detect these devices is 
```java
(BRAND.toLowerCase().contentEquals("energysistem") &&  MODEL.toLowerCase().startsWith("ereader"));
```
If I append that to EINK_ONYX my device is recognized as an onyx and I can switch between e-ink update modes and set an update interval. Since just one mode works I wonder if it is possible to add a new kind of device (for example EINK_RK3026) and don't provide an option to change the update mode in settings.

**Comment by buggins** [comment]
isn't sistem a misspelling? adding both sistem and system just in case

**Comment by pazos** [comment]
@buggins, yes sistem is a misspelling, but not mine, you could ask the company @ https://www.energysistem.com/en

**Comment by buggins** [comment]
EINK_ENERGYSYSTEM = (
			(BRAND.toLowerCase().contentEquals("energysistem")||BRAND.toLowerCase().contentEquals("energysystem")) &&  MODEL.toLowerCase().startsWith("ereader"));

I believe detection should work. Closing issue.
