### ISSUE TITLE
LICENSE file in the root of project

### ISSUE THREAD

**Issue by avsej** [buggins/coolreader#80]
Hi, would it be possible to create `LICENSE` or `COPYING` file in the root of the project with contents of https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt?

It will help packaging the project in some linux repositories

**Comment by link2xt** [comment]
By the way, it is not clear if CoolReader is [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) or [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html).
