### ISSUE TITLE
Custom font doesn't stick after losing focus [Android]

### ISSUE THREAD

**Issue by Kdio** [buggins/coolreader#81]
Android version 3.2.29-1

I've installed, long ago, a TTF font to the subdir of /.cr3/fonts but unfortunately after the app loses focus (goes background) and is called back (foreground) the default font comes back alive.

To resume the custom font I have to go **Options** >> **CSS** >> check **Enable document internal styles** >> resume reading and back to **Options** unchecking the previous option and then the custom font is back.

The font file is correctly registered and the **Font face** doesn't change ... it just doesn't stick.

This misbehavior started upon last update.

Please advise if this is not an app issue but a _user_ one.

Thanks.

**Comment by Kdio** [comment]
Just to confirm that a downgrade to 3.2.9-1 doesn't show the issue above described. Works flawlessly.

**Comment by circulosmeos** [comment]
Just to confirm that this is a version issue of 3.2.29-1, no matter what font.
Excellent app btw !

**Comment by virxkane** [comment]
Fixed in #83.
