### ISSUE TITLE
Cannot compile on Linux

### ISSUE THREAD

**Issue by probonopd** [buggins/coolreader#94]
This is my Travis CI build script:
https://github.com/probonopd/coolreader/blob/patch-1/.travis.yml

This is the complete build log:
https://api.travis-ci.com/v3/job/199509649/log.txt

```
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-misleading-indentation" [enabled by default]
[ 55%] Linking C static library libharfbuzz-subset.a
[ 55%] Built target harfbuzz-subset
[ 55%] Building CXX object crengine/CMakeFiles/crengine.dir/src/lvstream.cpp.o
In file included from /home/travis/build/probonopd/coolreader/crengine/src/../include/lvstream.h:32:0,
                 from /home/travis/build/probonopd/coolreader/crengine/src/lvstream.cpp:27:
/home/travis/build/probonopd/coolreader/crengine/src/../include/lvstring.h: In function ‘void LVRemovePathDelimiter(lString8&)’:
/home/travis/build/probonopd/coolreader/crengine/src/../include/lvstring.h:375:6: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
      if (pos > pchunk->len)
      ^
/home/travis/build/probonopd/coolreader/crengine/src/../include/lvstring.h:375:6: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
      if (pos > pchunk->len)
      ^
make[1]: *** [crengine/CMakeFiles/crengine.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by virxkane** [comment]
Actual error in your log:

> [ 51%] [32mBuilding CXX object crengine/CMakeFiles/crengine.dir/src/crgui.cpp.o[0m
> /home/travis/build/probonopd/coolreader/crengine/src/lvfntman.cpp:59:38: fatal error: freetype/config/ftheader.h: No such file or directory
>  #include <freetype/config/ftheader.h>

Include pathes for freetype in coolreader is non-stantard, so add next option to cmake:
-DCMAKE_CXX_FLAGS="-DUSE_FREETYPE2"
See crengine/src/lvfntman.cpp. In old freetype version, for example 2.5.2 in Ubuntu 14.04, headers placed in /usr/include/freetype2, in recent version - /usr/include/freetype2/freetype. I don't know when this changed.

**Comment by virxkane** [comment]
Also is a good idea replace `make -j$(nproc)` with `make -DVERBOSE=1 -j$(nproc)` for more verbose build log.

**Comment by virxkane** [comment]
Also you can use installed HarfBuzz library (`apt-get install libharfbuzz-dev`), but in Ubuntu 14.04 it's very old.

**Comment by probonopd** [comment]
Thank you, I was able to compile CoolReader and upload an AppImage for testing to https://github.com/probonopd/coolreader/releases/continuous/.

One thing that is not correct seems to be

```
2019/05/13 19:43:15.9970 ERROR Canot load translation file cr3_en_US from dir /usr/share/cr3/i18n/
2019/05/13 19:43:16.0825 ERROR Document cache index file cannot be read
2019/05/13 19:43:16.0972 ERROR Error opening file /usr/share/cr3/cr3.ini for reading
2019/05/13 19:43:16.0973 ERROR Cannot load settings from file /usr/share/cr3/cr3.ini
2019/05/13 19:43:16.0982 ERROR Error opening file /usr/share/cr3/cr3hist.bmk for reading
2019/05/13 19:43:16.0982 ERROR Error opening file /usr/share/cr3/fb2.css for reading
```

Instead of loading stuff from a hardcoded fixed loction at `/usr/share/`, these paths should be constructed relative to the main executable directory, e.g., using `QCoreApplication::applicationDirPath()`. Do you think this could be done?

Then it would work also when executed from locations such as `/tmp/.mount_CoolRe3iOBNY/usr/bin/coolreader`, and would load its resources from `/tmp/.mount_CoolRe3iOBNY/usr/share/coolreader/...`.


http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath

**Comment by virxkane** [comment]
Sorry, proper command to verbose build:
`make VERBOSE=1 -j$(nproc)`

**Comment by probonopd** [comment]
Sent a pull request at https://github.com/buggins/coolreader/pull/95.
